version: '3'
services:
  wallet-db:
    image: mongo
    ports: 
      - 27017:27017
    environment: 
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: usman1234

  mongo-express:
    image: mongo-express
    ports: 
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: usman1234
      ME_CONFIG_MONGODB_SERVER: wallet-db
  
      
  
